/*
 Author: Anya Marchenko
 Date: 3 July 2023

 This file cleans  
 
 Inputs: interim_complaints_11_17.dta generated by 0_setup
 
 */

/*******************************************************************************
* Load data saved from 0_setup.do
*******************************************************************************/

use "$data/interim_complaints_11_17.dta", clear 
  

generate random = runiform()
sort random 
generate insample = _n <= 34000


/*******************************************************************************
Clean variables 
*******************************************************************************/

* Clean date vars 
foreach var of varlist *date*{
	gen `var'_clean = date(`var', "MDY")
	format `var'_clean %td
}

gen sh = 1 if issue == "Sexual Harassment"
la var sh "=1 if complaintant issue == Sexual Harassment"

egen fiscal_year_group = group(fiscal_year)

graph bar (count) sh, over(fiscal_year) title("Number of SH charges filed per fiscal year")

graph bar (mean) total_benefit_amount if sh ==1, over(fiscal_year) title("Monetary benefit complaintant received in SH cases")

* N = 2,123, min is 21, max is 2234 days
gen days_to_resolution = resolution_date_clean - date_first_office_clean
sum days_to_resolution

* How SH cases ended
tab closure_action if sh ==1

* How many dates are missing?
misstable summarize *_clean if sh ==1
